### ISSUE TITLE
Different api for `File#delete` and `S3Storage#delete`

### ISSUE THREAD

**Issue by carlosipe** [rogercampos/saviour#22]
When using a `File` storage I can do: 
```ruby
class Model
  attach_file :image, Uploader
  ...
end

model.image.delete
```

If `image` file does not exist, nothing happens, see:
https://github.com/rogercampos/saviour/blob/master/lib/saviour/file.rb#L24

Instead when using S3Storage, doing the same thing it raises a RuntimeError
`RuntimeError: File does not exists`. See:
https://github.com/rogercampos/saviour/blob/master/lib/saviour/s3_storage.rb#L38

I think both should behave the same way, either raising an error in both cases, either silently ignoring the absence of file to be deleted.

Personally, I tend to think that is going to fit more cases doing just the latter. The meaning is "you wanted this file not to exist; it doesn't exist already so everything is fine". It's a bit more declarative instead of imperative.

**Comment by carlosipe** [comment]
Let me know what you think and I'll open a PR if you want me to :+1:

**Comment by rogercampos** [comment]
currently both raise an error if the file is not present:

https://github.com/rogercampos/saviour/blob/master/lib/saviour/s3_storage.rb#L38
https://github.com/rogercampos/saviour/blob/master/lib/saviour/local_storage.rb#L29

`File` is the class of any mounter, the storage for local filesystem is `LocalStorage`. 

About to fail or not, I choose to fail in order to catch possible bugs (seems incorrect to try to delete something that is not there?). But in any case I agree it's up to every specific use case to choose one thing or another. The storages abstraction is public api so any application can use their own storage class with their specific behaviors.

**Comment by carlosipe** [comment]
You're right. Sorry for this.
I didn't see it correctly, I tried to delete a file that didn't exist (which in carrierwave's API doesn't complain), I said "oh, saviour has a different API", I checked the code and saw the difference between `File` and `S3Storage` without noticing that the storage for local filesystem was actually `LocalStorage`.

Closing the issue. Thanks!
